FROM golang:1.19.1  AS BUILDER

WORKDIR /src/
COPY . .


RUN go build -o ./webapi ./cmd/webapi

FROM debian:bookworm 

EXPOSE 3000


WORKDIR /app/
COPY --from=builder /src/webapi /app/webapi 

CMD ["/app/webapi"]
