FROM golang:1.19.1

WORKDIR /src/
COPY . .


RUN go build -o ./webapi ./cmd/webapi

FROM debian:bookworm 

RUN apt-get update && apt-get install -y golang
EXPOSE 3000


WORKDIR /app/
RUN go build -o ./webapi ./cmd/webapi
COPY --from=builder /src/webapi /app/

CMD ["/src/webapi"]
